import { Lead } from '@/types'

export const MOCK_LEADS: Lead[] = [
  {
    id: 'mock-1',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    status: 'new',
    score: 'hot',
    name: 'Ayşe Kaya',
    company: 'ModaStore',
    role: 'CEO',
    email: 'ayse@modasstore.com',
    companySize: '50-100 kişi',
    currentTool: 'Google Analytics + Excel',
    painPoint: 'Ürün bazlı dönüşüm oranlarını takip edemiyoruz, hangi ürünün neden satmadığını anlamak çok zaman alıyor',
    timeline: 'Bu ay içinde karar vermek istiyoruz',
    intent: 'demo',
    conversationSummary: 'ModaStore CEO\'su Ayşe Hanım, 50-100 kişilik ekibiyle ürün bazlı analitik sorunu yaşıyor. Google Analytics yetersiz kalıyor, bu ay içinde geçiş yapmak istiyor. Acil ve bilinçli bir talep.',
    messages: [
      { role: 'assistant', content: 'Merhaba! Ben NextReach\'in dijital asistanıyım. Size nasıl yardımcı olabilirim?' },
      { role: 'user', content: 'Merhaba, analitik dashboard\'unuz hakkında bilgi almak istiyorum' },
      { role: 'assistant', content: 'Harika! Sizi tanıyabilir miyim? Adınız ve şirketiniz nedir?' },
      { role: 'user', content: 'Ayşe Kaya, ModaStore CEO\'suyum' },
    ],
    rawConversation: 'NextReach: Merhaba!\nZiyaretçi: Merhaba, analitik dashboard hakkında bilgi almak istiyorum\nNextReach: Sizi tanıyabilir miyim?\nZiyaretçi: Ayşe Kaya, ModaStore CEO\'suyum',
  },
  {
    id: 'mock-2',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: 'contacted',
    score: 'warm',
    name: 'Mehmet Demir',
    company: 'TechShop',
    role: 'Pazarlama Müdürü',
    email: 'mehmet@techshop.com.tr',
    companySize: '20-50 kişi',
    currentTool: 'Shopify Analytics',
    painPoint: 'Pazarlama kampanyalarının gerçek ROI\'sini ölçemiyoruz',
    timeline: 'Q3\'te bütçe var',
    intent: 'fiyat',
    conversationSummary: 'TechShop pazarlama müdürü kampanya ROI takibi için başvurdu. Shopify Analytics yetersiz kalıyor. Q3\'te bütçesi var, acil değil ama bilinçli.',
    messages: [],
    rawConversation: '',
  },
  {
    id: 'mock-3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    status: 'new',
    score: 'cold',
    name: 'Ali',
    company: undefined,
    role: undefined,
    email: undefined,
    companySize: undefined,
    currentTool: undefined,
    painPoint: 'Genel bilgi almak istedim',
    timeline: undefined,
    intent: 'bilgi',
    conversationSummary: 'Sadece "Ali" adını verdi, şirket veya iletişim bilgisi yok. Genel bilgi talebi, takip önceliği düşük.',
    messages: [],
    rawConversation: '',
  },
  {
    id: 'mock-4',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    status: 'qualified',
    score: 'hot',
    name: 'Zeynep Arslan',
    company: 'BeautyWorld',
    role: 'CTO',
    email: 'zeynep@beautyworld.com',
    companySize: '100-200 kişi',
    currentTool: 'Özel geliştirme + Tableau',
    painPoint: 'Mevcut sistem bakımı çok pahalı ve yavaş, hazır bir çözüme geçmek istiyoruz',
    timeline: 'Hemen başlamak istiyoruz',
    intent: 'demo',
    conversationSummary: 'BeautyWorld CTO\'su mevcut pahalı özel sistemi bırakıp hazır çözüme geçmek istiyor. 100-200 kişilik şirket, hemen başlamak istiyor. Yüksek öncelikli.',
    messages: [],
    rawConversation: '',
  },
]
